name: dart_ln
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies: 
  grpc: ^3.0.2
  json_rpc_2: ^3.0.1
  protobuf: ^2.0.1
  

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
